name: Test GraalJS Gradle Webpack Guide

on:
  push:
    paths:
      - 'graaljs/graaljs-gradle-webpack-guide/**'
      - '.github/workflows/graaljs-gradle-webpack-guide.yml'
  pull_request:
    paths:
      - 'graaljs/graaljs-gradle-webpack-guide/**'
      - '.github/workflows/graaljs-gradle-webpack-guide.yml'
  workflow_dispatch:

permissions:
  contents: read
jobs:
  run:
    name: 'graaljs-gradle-webpack-guide'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24.0.1'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'
      - name: Build and run 'graaljs-gradle-webpack-guide'
        run: |
          cd graaljs/graaljs-gradle-webpack-guide
          ./gradlew build
          ./gradlew run --args="https://www.graalvm.org/javascript"
